### PR TITLE
Add new portfolio tracking software: Ghostfolio

### PR DESCRIPTION
**Pull request by dtslvr**

### CODE REVIEW

**Review by ashishb — APPROVED** [review]

**Comment by ashishb** [comment]
Thanks for the contribution.

**Comment by dtslvr** [comment]
You're welcome @ashishb. You don't like to merge it?

**Comment by ashishb** [comment]
> You're welcome @ashishb. You don't like to merge it?

Missed by mistake. Merged now.

**Comment by dtslvr** [comment]
> Missed by mistake. Merged now.

No problem 😃

**Pull request merged**
